### ISSUE TITLE
extension/node_modules/botframework-webchat/lib"' has no exported member 'DirectLine' and App

### ISSUE THREAD

**Issue by OneAman** [withum-digital/directline-bot-extension#1]
Hi Team,

Thank you for the great work, 

I cloned this webpart and installed  "npm install botframework-webchat", however i can't find App and Directline members in this folder.

![Annotation 2019-09-10 145522](https://user-images.githubusercontent.com/22772611/64590843-0b284d80-d3db-11e9-9267-d0acf7f27dfc.gif)

can you please help me sort this out.

Thank you
Aman

**Comment by pdemro** [comment]
@LuckycSharp did you try just running npm i from the project directory?  It should install all the required packages

`npm i`

**Comment by pdemro** [comment]
Closing because cannot reproduce/inactivity
