### ISSUE TITLE
A few updates I needed to make to get it working

### ISSUE THREAD

**Issue by scallin** [withum-digital/directline-bot-extension#2]
Hi, I cloned the repository and followed the instructions but had to make a few tweaks to get it working.

1. After cloning and running **npm i** I got the following error: **npm ERR! code 404 Not Found: @uifabric/foundation@0.109.2** which doesn't seem to be a version.

![image](https://user-images.githubusercontent.com/20932971/64636765-686ad180-d3d0-11e9-844d-0c9e996e636f.png)

To fix it I manually installed the latest lts version:
**npm i @uifabric/foundation@0.8.3 --save**

2. The instruction say to use **&customActions={"21d2dffd-4f4e-461c-99d4-047c10b21d19"** in the URL to test in the workbench - but is should be **&customActions={"15be81a7-b6b8-4a75-8de3-0da288492e77"**

**Comment by pdemro** [comment]
Thank you for the feedback @scallin!  I will try to integrate these updates when I have some time

**Comment by pdemro** [comment]
I updated the documentation to resolve the discrepency.  

I was not able to reproduce the first issue you mentioned about the @uifabric/foundation@0.109.2 package.  If it remains an issue lets research this more closely
