### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by MarcusMLarsson** [withum-digital/directline-bot-extension#4]
I get the following error when running npm install.

npm ERR! notarget No matching version found for @uifabric/foundation@0.109.2
npm WARN tar ENOENT: no such file or directory 

Any ideas?

**Comment by MarcusMLarsson** [comment]
It works if I add the following to package.json. 

    "@uifabric/azure-themes": "^7.0.2",
    "@uifabric/charting": "^0.131.2",
    "@uifabric/file-type-icons": "^7.0.3",
    "@uifabric/fluent-theme": "^7.0.2",
    "@uifabric/foundation": "^7.0.1",
    "@uifabric/icons": "^7.0.2",
    "@uifabric/merge-styles": "^7.0.2",
    "@uifabric/set-version": "^7.0.0",
    "@uifabric/styling": "^7.0.2",
    "@uifabric/theme-samples": "^7.0.2",
    "@uifabric/utilities": "^7.0.3",
    "@uifabric/variants": "^7.0.2"

**Comment by OmarStewey** [comment]
run this first:
npm i @uifabric/foundation --save

**Comment by MarcusMLarsson** [comment]
Thank you, it works 👍 . Any idea how to make it work on SPFx 1.4.1 rather than 1.8.2?

**Comment by pdemro** [comment]
I have made an update to the project shrinkwrap file which removes references to this deprecated version of @uifabric/foundation.  

@MarcusMLarsson Feel free to DM me if you or your company needs help porting this to 1.4.1, or help in upgrading your project to the latest SpFx package (which, keep in mind, is 1.10 and not this package's version of 1.8.1)
